
reference:
  background: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Background/background_panel_cfDNA_novaseqX_24.tsv"
  artifacts: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Artifact/artifact_panel_cfDNA_novaseqX_24.tsv"
  design_intervals_gatk_cnv: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/gatk.preprocessed.cfDNA_novaseqX_24.interval_list"
  
cnvkit_batch:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/cnvkit_cfDNA_novaseqX_24.cnn"

gatk_denoise_read_counts:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/gatk_cnv_cfDNA_novaseqX_24.hdf5"

jumble_run:
  normal_reference: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/jumble/jumble_cfDNA_novaseqX_24.RDS"

msisensor_pro:
  PoN: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/Msisensor_pro_reference_cfDNA_novaseqX_24.list_baseline"

msisensor_pro_filter_sites:
  PoN: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/PoN/Msisensor_pro_reference_cfDNA_novaseqX_24.list_baseline"

purecn:
  extra: "--model betabin --mapping-bias-file /projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/mapping_bias_cfDNA_novaseqX_24.rds"
  normaldb: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/normalDB_cfDNA_novaseqX_24.rds"
  intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/targets_twist-gms-st_hg19_25000_cfDNA_novaseqX_intervals.txt"

purecn_coverage:
  intervals: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/purecn/targets_twist-gms-st_hg19_25000_cfDNA_novaseqX_intervals.txt"

tmb_umi:
  artifacts: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/Artifact/artifact_panel_cfDNA_novaseqX_24.tsv"


